# **Introduction**

## **Problem Statement**

In the competitive e-commerce market, timely delivery is crucial for customer satisfaction. The E-commerce platform aims to predict which orders are likely to be delivered late, enabling proactive measures to be taken to mitigate delays and enhance customer satisfaction.

By understanding the factors contributing to late deliveries, the platform can optimize its logistics, improve communication with customers, and reduce the impact of delays on customer experience.

## **Objective**

Predict if an order will be delivered on time or delayed based on order attributes.

## Dataset Overview

The E-commerce Order Dataset provides comprehensive information related to orders, items within orders, customers, payments, and products for an e-commerce platform. This dataset is structured with multiple tables, each containing specific information about various aspects of the e-commerce operations.

#### **Orders Table:**
*   order_id: Unique identifier for an order, acting as the primary key.

*   customer_id: Unique identifier for a customer. This table may not be unique at this level.

*   order_status: Indicates the status of an order (e.g., delivered, cancelled, processing, etc.).

*   order_purchase_timestamp: Timestamp when the order was made by the customer.

*   order_approved_at: Timestamp when the order was approved from the seller's side.

*   order_delivered_timestamp: Timestamp when the order was delivered at the customer's location.

*   order_estimated_delivery_date: Estimated date of delivery shared with the customer while placing the order.

### **Order Items Table:**
*   order_id: Unique identifier for an order.

*   order_item_id: Item number in each order, acting as part of the primary key along with the order_id.

*   product_id: Unique identifier for a product.

*   seller_id: Unique identifier for the seller.

*   price: Selling price of the product.

*   shipping_charges: Charges associated with the shipping of the product.

### **Customers Table:**
*  customer_id: Unique identifier for a customer, acting as the primary key.

*  customer_zip_code_prefix: Customer's Zip code.

*  customer_city: Customer's city.

*  customer_state: Customer's state.

### **Payments Table:**
*  order_id: Unique identifier for an order.

*  payment_sequential: Provides information about the sequence of payments for the given order.

*  payment_type: Type of payment (e.g., credit_card, debit_card, etc.).

*  payment_installments: Payment installment number in case of credit cards.

*  payment_value: Transaction value.
Products Table

*  product_id: Unique identifier for each product, acting as the primary key.
product_category_name: Name of the category the product belongs to.

*  product_weight_g: Product weight in grams.

*  product_length_cm: Product length in centimeters.

*  product_height_cm: Product height in centimeters.
product_width_cm: Product width in centimeters.

# **Data Understanding**

## Import libraries

In [1]:
import pandas as pd
import holidays

## **Load the Data**

In [2]:
customers = pd.read_csv('/kaggle/input/ecommerce-order-dataset/Ecommerce Order Dataset/train/df_Customers.csv')
order_items = pd.read_csv('/kaggle/input/ecommerce-order-dataset/Ecommerce Order Dataset/train/df_OrderItems.csv')
orders = pd.read_csv('/kaggle/input/ecommerce-order-dataset/Ecommerce Order Dataset/train/df_Orders.csv')
payments = pd.read_csv('/kaggle/input/ecommerce-order-dataset/Ecommerce Order Dataset/train/df_Payments.csv')
products = pd.read_csv('/kaggle/input/ecommerce-order-dataset/Ecommerce Order Dataset/train/df_Products.csv')

In [3]:
# drop duplicate values
customers = customers.drop_duplicates()
order_items = order_items.drop_duplicates()
orders = orders.drop_duplicates()
payments = payments.drop_duplicates()
products = products.drop_duplicates()

In [4]:
# Merge Orders and Customers tables using left join
data = pd.merge(orders, customers, on='customer_id', how='left')

# Merge the result with Order Items table using left join
data = pd.merge(data, order_items, on='order_id', how='left')

# Merge the result with Payments table using left join
data = pd.merge(data, payments, on='order_id', how='left')

# Merge the result with Products table using left join
data = pd.merge(data, products, on='product_id', how='left')

print(data.shape)

(89316, 23)

## **Explore the data**

In [5]:
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,shipping_charges,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,84.65,1,credit_card,1,259.14,toys,491.0,19.0,12.0,16.0
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,3112,armacao dos buzios,RJ,...,23.79,1,credit_card,8,382.39,watches_gifts,440.0,18.0,14.0,17.0
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,4119,jandira,SP,...,17.38,1,credit_card,4,249.25,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,18212,uberlandia,MG,...,30.72,1,credit_card,2,27.79,toys,1450.0,68.0,3.0,48.0
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,88868,ilhabela,SP,...,30.66,1,credit_card,1,76.15,toys,300.0,17.0,4.0,12.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
 7   customer_zip_code_prefix       89316 non-null  int64
 8   customer_city                  89316 non-null  object
 9   customer_state                 89316 non-null  object
 10  product_id                     89316 non-null  object
 11  seller_id                      89316 non-null  object
 12  price                          89316 non-null  float64
 13  shipping_charges               89316 non-null  float64
 14  payment_sequential             89316 non-null  int64
 15  payment_type                   89316 non-null  object
 16  payment_installments           89316 non-null  int64
 17  payment_value                  89316 non-null  float64
 18  product_category_name          89008 non-null  object
 19  product_weight_g               89301 non-null  float64
 20  product_length_cm              89301 non-null  float64
 21  product_height_cm              89301 non-null  float64
 22  product_width_cm               89301 non-null  float64
dtypes: float64(7), int64(3), object(13)
memory usage: 15.7+ MB

# **Data Cleaning and Preparation**

## Data Type Conversion

In [7]:
data['order_purchase_timestamp'] = pd.to_datetime(data['order_purchase_timestamp'])
data['order_approved_at'] = pd.to_datetime(data['order_approved_at'])
data['order_delivered_timestamp'] = pd.to_datetime(data['order_delivered_timestamp'])
data['order_estimated_delivery_date'] = pd.to_datetime(data['order_estimated_delivery_date'])

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  datetime64[ns]
 4   order_approved_at              89307 non-null  datetime64[ns]
 5   order_delivered_timestamp      87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date  89316 non-null  datetime64[ns]
 7   customer_zip_code_prefix       89316 non-null  int64
 8   customer_city                  89316 non-null  object
 9   customer_state                 89316 non-null  object
 10  product_id                     89316 non-null  object
 11  seller_id                      89316 non-null  object
 12  price                          89316 non-null  float64
 13  shipping_charges               89316 non-null  float64
 14  payment_sequential             89316 non-null  int64
 15  payment_type                   89316 non-null  object
 16  payment_installments           89316 non-null  int64
 17  payment_value                  89316 non-null  float64
 18  product_category_name          89008 non-null  object
 19  product_weight_g               89301 non-null  float64
 20  product_length_cm              89301 non-null  float64
 21  product_height_cm              89301 non-null  float64
 22  product_width_cm               89301 non-null  float64
dtypes: datetime64[ns](4), float64(7), int64(3), object(9)
memory usage: 15.7+ MB

## Handling missing values

#### **exploring null values in order_delivered_timestamp columns:**

In [9]:
missing = data[data['order_delivered_timestamp'].isnull()]
missing

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,shipping_charges,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
15,P5R6jr1qZdh4,FrEvnEiMKGpr,canceled,2017-07-24 11:38:43,2017-07-24 11:50:18,NaT,2017-08-07,28630,sao paulo,SP,...,14.91,1,credit_card,10,98.42,toys,4000.0,45.0,20.0,100.0
41,C21fWds5zL0W,iFsAJRrzVaTS,shipped,2017-02-04 12:58:55,2017-02-04 13:10:38,NaT,2017-03-15,4932,sao paulo,SP,...,27.80,1,credit_card,7,107.82,toys,1500.0,18.0,35.0,48.0
86,vSug5AqRo9gE,oWBBqGwqpx4m,shipped,2017-05-07 10:22:58,2017-05-09 09:35:20,NaT,2017-06-12,75630,bom jesus,PI,...,63.17,1,wallet,1,310.20,toys,4105.0,67.0,10.0,67.0
89,2HQ26ShSPhCA,uvuFFZDOAlU7,canceled,2017-07-29 12:56:17,2017-07-29 13:05:18,NaT,2017-08-18,93410,sao paulo,SP,...,24.78,6,voucher,1,81.16,toys,1590.0,38.0,20.0,23.0
133,1By8LOosrvF2,grsbZ5L1H5ty,canceled,2017-11-06 15:47:20,2017-11-07 07:30:29,NaT,2017-11-28,19030,monte carmelo,MG,...,104.16,1,wallet,1,197.91,toys,50.0,42.0,9.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89196,VP3EBMExdh7K,acB2XNtto2SX,shipped,2018-01-24 18:19:18,2018-01-24 18:37:41,NaT,2018-03-01,48610,itapipoca,CE,...,16.94,1,credit_card,5,189.96,toys,1150.0,40.0,8.0,32.0
89226,0jPFvDPItbRN,Hb5m8q1YZEfv,canceled,2017-08-02 14:08:18,2017-08-02 14:23:13,NaT,2017-08-24,95560,jundiai,SP,...,4.75,1,credit_card,1,323.34,toys,500.0,30.0,10.0,20.0
89234,QzxMjvdMpOEI,yCbzy1m4tTUA,shipped,2017-09-15 09:05:41,2017-09-15 09:15:13,NaT,2017-10-05,18380,sao goncalo,RJ,...,46.76,1,credit_card,1,665.87,toys,1850.0,37.0,22.0,40.0
89262,rnnNWGgyHsA5,6LYRxLvrUzNy,canceled,2017-12-13 12:55:38,2017-12-13 13:11:58,NaT,2018-01-02,95925,sao paulo,SP,...,30.56,1,credit_card,1,205.20,toys,430.0,38.0,12.0,20.0
89281,YCJoeAvBWkpq,BaZgf4zWhXSS,shipped,2018-03-06 11:13:39,2018-03-06 11:30:38,NaT,2018-03-16,97546,sao paulo,SP,...,15.19,1,credit_card,1,101.12,toys,200.0,16.0,2.0,11.0

**Canceled Orders:** For orders with a status of "canceled," it makes sense that the order_delivered_timestamp is missing (NaN) because the order was never delivered.

**Shipped Orders:** For orders with a status of "shipped," the NaN value could indicate that the order has not yet been delivered at the time of data extraction, or the delivery timestamp wasn't recorded properly.

In [10]:
# Impute null values in product_category_name with 'unknown'
data['product_category_name'].fillna('unknown', inplace=True)

/tmp/ipykernel_36/35130888.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['product_category_name'].fillna('unknown', inplace=True)

In [11]:
# Calculate the mean values for the 'toys' category
mean_weight = data[data['product_category_name'] == 'toys']['product_weight_g'].mean()
mean_length = data[data['product_category_name'] == 'toys']['product_length_cm'].mean()
mean_height = data[data['product_category_name'] == 'toys']['product_height_cm'].mean()
mean_width = data[data['product_category_name'] == 'toys']['product_width_cm'].mean()

# Impute missing values with the calculated means
data.loc[(data['product_category_name'] == 'toys') & (data['product_weight_g'].isnull()), 'product_weight_g'] = mean_weight
data.loc[(data['product_category_name'] == 'toys') & (data['product_length_cm'].isnull()), 'product_length_cm'] = mean_length
data.loc[(data['product_category_name'] == 'toys') & (data['product_height_cm'].isnull()), 'product_height_cm'] = mean_height
data.loc[(data['product_category_name'] == 'toys') & (data['product_width_cm'].isnull()), 'product_width_cm'] = mean_width

In [12]:
# Filter the data to show only rows where product_category_name is 'toys'
toys_data = data[data['order_approved_at'].isnull()]
toys_data

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,shipping_charges,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
10788,4Itts2TBUQzs,Z3dI7uRBfJOD,delivered,2017-02-17 13:05:55,NaT,2017-03-02 11:09:19,2017-03-20,60441,macae,RJ,...,24.11,1,wallet,1,181.69,cool_stuff,1200.0,42.0,25.0,15.0
16137,6MPB830Ufh0n,SOtqXN1MqcLj,delivered,2017-02-17 17:21:55,NaT,2017-03-03 12:16:03,2017-03-20,45790,abaete,MG,...,48.99,1,wallet,1,96.88,toys,4300.0,36.0,13.0,20.0
28951,lqW95yj4n1Qd,jCPmhkcyVR1z,delivered,2017-02-18 15:52:27,NaT,2017-03-07 13:57:47,2017-03-29,60731,paraisopolis,MG,...,34.60,1,wallet,1,707.72,toys,1200.0,30.0,5.0,20.0
30494,dn1i9D4DFVZ2,Es95IGZCDDXy,delivered,2017-02-17 15:53:27,NaT,2017-03-03 11:47:47,2017-03-23,5269,sao vendelino,RS,...,45.27,1,wallet,1,115.40,toys,2700.0,42.0,11.0,36.0
41752,vBZCEuCG9Hf1,zHEH7vdeO6UZ,delivered,2017-02-18 11:04:19,NaT,2017-03-02 16:15:23,2017-03-22,76560,varzea paulista,SP,...,55.54,1,wallet,1,622.42,toys,300.0,16.0,15.0,15.0
42772,PXwPIjmXCehX,gjKhFw8AFnW1,delivered,2017-02-18 16:48:35,NaT,2017-03-09 07:28:47,2017-03-31,2067,caninde,CE,...,67.33,1,wallet,1,258.08,cool_stuff,1200.0,42.0,25.0,15.0
47768,Yg9HDkWtA3Q3,GFg4QWN26cLs,delivered,2017-02-19 01:28:47,NaT,2017-03-02 03:41:58,2017-03-27,72311,sao paulo,SP,...,83.60,1,wallet,1,93.52,toys,1700.0,33.0,8.0,23.0
59434,hynO4uEubWbe,QdQBjy8APVMg,delivered,2017-02-18 14:40:00,NaT,2017-03-01 13:25:33,2017-03-17,80630,cotia,SP,...,62.45,1,wallet,1,31.43,toys,20800.0,75.0,40.0,40.0
65247,Uso7EoEPMrLU,rKJOxQc2PTfc,delivered,2017-01-19 22:26:59,NaT,2017-02-06 14:22:19,2017-03-16,5707,conselheiro lafaiete,MG,...,2.46,1,wallet,1,530.47,toys,600.0,30.0,3.0,20.0

In [13]:
# Calculate the time difference between 'order_approved_at' and 'order_purchase_timestamp'
data['approval_time_diff'] = (data['order_approved_at'] - data['order_purchase_timestamp']).dt.total_seconds()

# Calculate the mean of the time differences in seconds
mean_approval_time_diff = data['approval_time_diff'].mean()

# Impute missing 'order_approved_at' by adding the mean difference to 'order_purchase_timestamp'
data.loc[data['order_approved_at'].isnull(), 'order_approved_at'] = data['order_purchase_timestamp'] + pd.to_timedelta(mean_approval_time_diff, unit='s')

# Drop the temporary column used for calculation
data = data.drop(columns=['approval_time_diff'])

In [14]:
# Drop rows where 'order_delivered_timestamp' is null
data = data.dropna(subset=['order_delivered_timestamp'])

# Verify the result
print(f"Number of remaining rows: {len(data)}")

Number of remaining rows: 87427

In [15]:
# Check for missing values in each column
missing_values = data.isnull().sum()
# Display the missing values
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_timestamp        0
order_estimated_delivery_date    0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
product_id                       0
seller_id                        0
price                            0
shipping_charges                 0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
product_category_name            0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
dtype: int64

## **feature engineering**

### is_delayed

In [16]:
def label_delivery_status(row):
    if pd.notna(row['order_delivered_timestamp']) and row['order_status'] == "delivered":
        return 1 if row['order_delivered_timestamp'] > row['order_estimated_delivery_date'] else 0
    return None

data['is_delayed'] = data.apply(label_delivery_status, axis=1)

In [17]:
delivery_status_counts = data['is_delayed'].value_counts()

# Print the counts
print(delivery_status_counts)

is_delayed
0.0    80685
1.0     6737
Name: count, dtype: int64

### delivery_days_diff

In [18]:
data['delivery_days_diff'] = (data['order_delivered_timestamp'] - data['order_estimated_delivery_date']).dt.days

### processing_time

In [19]:
data['processing_time'] = data['order_approved_at'] - data['order_purchase_timestamp']
data['processing_time_seconds'] = data['processing_time'].dt.total_seconds()
def categorize_processing_time(seconds):
    if seconds <= 600:  #   10 minutes
        return 'fast'
    elif 600 < seconds <= 3600:  #   10-60 minutes
        return 'medium'
    else:
        return 'slow'

data['processing_time_category'] = data['processing_time_seconds'].apply(categorize_processing_time)

In [20]:
processing_time_category_counts = data['processing_time_category'].value_counts()

# Print the counts
print(processing_time_category_counts)

processing_time_category
medium    47258
slow      31695
fast       8474
Name: count, dtype: int64

In [21]:
data.drop(columns=['processing_time', 'processing_time_seconds'], inplace=True)
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,payment_installments,payment_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,is_delayed,delivery_days_diff,processing_time_category
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,1,259.14,toys,491.0,19.0,12.0,16.0,0.0,-14,medium
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,3112,armacao dos buzios,RJ,...,8,382.39,watches_gifts,440.0,18.0,14.0,17.0,0.0,-21,medium
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,4119,jandira,SP,...,4,249.25,costruction_tools_garden,2200.0,16.0,16.0,16.0,0.0,-9,slow
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,18212,uberlandia,MG,...,2,27.79,toys,1450.0,68.0,3.0,48.0,0.0,-23,medium
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,88868,ilhabela,SP,...,1,76.15,toys,300.0,17.0,4.0,12.0,0.0,-13,medium

Longer processing times may contribute to delays in delivery.

### order_estimated_delivery_is_weekend

In [22]:
data['order_estimated_delivery_day_of_week'] = data['order_delivered_timestamp'].dt.weekday
data['order_estimated_delivery_is_weekend'] = data['order_estimated_delivery_day_of_week'].apply(lambda x: 1 if x >= 5 else 0)
data.drop(columns=['order_estimated_delivery_day_of_week'], inplace=True)
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,payment_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,is_delayed,delivery_days_diff,processing_time_category,order_estimated_delivery_is_weekend
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,259.14,toys,491.0,19.0,12.0,16.0,0.0,-14,medium,0
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,3112,armacao dos buzios,RJ,...,382.39,watches_gifts,440.0,18.0,14.0,17.0,0.0,-21,medium,0
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,4119,jandira,SP,...,249.25,costruction_tools_garden,2200.0,16.0,16.0,16.0,0.0,-9,slow,0
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,18212,uberlandia,MG,...,27.79,toys,1450.0,68.0,3.0,48.0,0.0,-23,medium,0
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,88868,ilhabela,SP,...,76.15,toys,300.0,17.0,4.0,12.0,0.0,-13,medium,0

### is_order_estimated_delivery_holiday

In [23]:
brzl_holidays = holidays.Brazil()

# Ensure that the 'order_delivered_timestamp' column is in datetime format
data['order_delivered_timestamp'] = pd.to_datetime(data['order_delivered_timestamp'])

# Create a new column that checks if the delivered timestamp is a holiday, skipping NaN values
data['is_order_estimated_delivery_holiday'] = data['order_delivered_timestamp'].apply(
    lambda x: x.date() in brzl_holidays if pd.notnull(x) else False
)

# Display the first few rows to inspect the new column
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,is_delayed,delivery_days_diff,processing_time_category,order_estimated_delivery_is_weekend,is_order_estimated_delivery_holiday
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,toys,491.0,19.0,12.0,16.0,0.0,-14,medium,0,False
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,3112,armacao dos buzios,RJ,...,watches_gifts,440.0,18.0,14.0,17.0,0.0,-21,medium,0,False
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,4119,jandira,SP,...,costruction_tools_garden,2200.0,16.0,16.0,16.0,0.0,-9,slow,0,False
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,18212,uberlandia,MG,...,toys,1450.0,68.0,3.0,48.0,0.0,-23,medium,0,False
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,88868,ilhabela,SP,...,toys,300.0,17.0,4.0,12.0,0.0,-13,medium,0,False

In [24]:
is_purchase_holiday_counts = data['is_order_estimated_delivery_holiday'].value_counts()

# Print the counts
print(is_purchase_holiday_counts)

is_order_estimated_delivery_holiday
False    86771
True       656
Name: count, dtype: int64

### estimated_delivery_month

In [25]:
data['estimated_delivery_month'] = data['order_estimated_delivery_date'].dt.month

### product_size_category

In [26]:
data['product_volume_cm3'] = data['product_length_cm'] * data['product_height_cm'] * data['product_width_cm']

def categorize_product(row):
    if row['product_volume_cm3'] <= 2000 and row['product_weight_g'] <= 1000:
        return 'small'
    elif 2000 < row['product_volume_cm3'] <= 8000 and row['product_weight_g'] <= 5000:
        return 'medium'
    else:
        return 'large'

data['product_size_category'] = data.apply(categorize_product, axis=1)

In [27]:
data = data.drop(['product_volume_cm3','product_weight_g','product_length_cm','product_height_cm','product_width_cm'], axis=1)

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87427 entries, 0 to 89315
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_id                             87427 non-null  object
 1   customer_id                          87427 non-null  object
 2   order_status                         87427 non-null  object
 3   order_purchase_timestamp             87427 non-null  datetime64[ns]
 4   order_approved_at                    87427 non-null  datetime64[ns]
 5   order_delivered_timestamp            87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date        87427 non-null  datetime64[ns]
 7   customer_zip_code_prefix             87427 non-null  int64
 8   customer_city                        87427 non-null  object
 9   customer_state                       87427 non-null  object
 10  product_id                           87427 non-null  object
 11  seller_id                            87427 non-null  object
 12  price                                87427 non-null  float64
 13  shipping_charges                     87427 non-null  float64
 14  payment_sequential                   87427 non-null  int64
 15  payment_type                         87427 non-null  object
 16  payment_installments                 87427 non-null  int64
 17  payment_value                        87427 non-null  float64
 18  product_category_name                87427 non-null  object
 19  is_delayed                           87422 non-null  float64
 20  delivery_days_diff                   87427 non-null  int64
 21  processing_time_category             87427 non-null  object
 22  order_estimated_delivery_is_weekend  87427 non-null  int64
 23  is_order_estimated_delivery_holiday  87427 non-null  bool
 24  estimated_delivery_month             87427 non-null  int32
 25  product_size_category                87427 non-null  object
dtypes: bool(1), datetime64[ns](4), float64(4), int32(1), int64(5), object(11)
memory usage: 17.1+ MB

## Weather

In [29]:
weather = pd.read_csv('/kaggle/input/conventional-weather-stations-brazil/conventional_weather_stations_inmet_brazil_1961_2019.csv', sep=";")  # Your weather data
weather_stations = pd.read_csv('/kaggle/input/conventional-weather-stations-brazil/weather_stations_codes.csv', sep=";")  # Weather stations data

In [37]:
min_date = filtered_weather['Data'].min()
max_date = filtered_weather['Data'].max()

print("Min:", min_date)
print("Max:", max_date)

Min: 2016-10-27 00:00:00
Max: 2018-10-25 00:00:00

In [34]:
# Convert 'Data' column to datetime with day first format
weather['Data'] = pd.to_datetime(weather['Data'], dayfirst=True, errors='coerce')

# Define the min and max date range
min_date = '2016-10-27'
max_date = '2018-10-25'

# Filter the DataFrame to keep rows within the date range
filtered_weather = weather[(weather['Data'] >= min_date) & (weather['Data'] <= max_date)]

# Check the result
filtered_weather.info()

<class 'pandas.core.frame.DataFrame'>
Index: 431371 entries, 45008 to 12250038
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Estacao                    431371 non-null  int64
 1   Data                       431371 non-null  datetime64[ns]
 2   Hora                       431371 non-null  int64
 3   Precipitacao               152373 non-null  float64
 4   TempBulboSeco              409642 non-null  float64
 5   TempBulboUmido             319340 non-null  float64
 6   TempMaxima                 134249 non-null  float64
 7   TempMinima                 143712 non-null  float64
 8   UmidadeRelativa            407236 non-null  float64
 9   PressaoAtmEstacao          361460 non-null  float64
 10  PressaoAtmMar              338462 non-null  float64
 11  DirecaoVento               367991 non-null  float64
 12  VelocidadeVento            341740 non-null  float64
 13  Insolacao                  127230 non-null  float64
 14  Nebulosidade               415780 non-null  float64
 15  Evaporacao Piche           107370 non-null  float64
 16  Temp Comp Media            123647 non-null  float64
 17  Umidade Relativa Media     129246 non-null  float64
 18  Velocidade do Vento Media  123473 non-null  float64
 19  Unnamed: 19                0 non-null       float64
dtypes: datetime64[ns](1), float64(17), int64(2)
memory usage: 69.1 MB

In [35]:
print(weather.shape)
print(C.shape)

(12251335, 20)
(431371, 20)

In [86]:
weather_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Nome                265 non-null    object
 1   Código              265 non-null    int64
 2   Latitude            265 non-null    float64
 3   Longitude           265 non-null    float64
 4   Altitude            265 non-null    float64
 5   Status da Operação  265 non-null    object
 6   Ínicio da Operação  265 non-null    object
dtypes: float64(3), int64(1), object(3)
memory usage: 14.6+ KB

In [39]:
data['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date']).dt.strftime('%d/%m/%Y')
filtered_weather['Data'] = pd.to_datetime(filtered_weather['Data'], format='%d/%m/%Y')

/tmp/ipykernel_36/988577333.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_weather['Data'] = pd.to_datetime(filtered_weather['Data'], format='%d/%m/%Y')

In [40]:
filtered_weather = filtered_weather.merge(weather_stations, left_on='Estacao', right_on='Código')

In [44]:
data['customer_state'].unique()

array(['SP', 'RJ', 'MG', 'SC', 'ES', 'RN', 'BA', 'DF', 'RS', 'PE', 'GO',
       'CE', 'PR', 'MA', 'PI', 'MT', 'MS', 'SE', 'RO', 'TO', 'AM', 'AP',
       'PB', 'PA', 'AL', 'AC', 'RR'], dtype=object)

In [43]:
filtered_weather['State'].unique()

array(['RR', 'AM', 'AP', 'PA', 'MA', 'PI', 'SE', 'BA', 'MT', 'TO', 'MG',
       'SP', 'ES', 'RJ', 'MS', 'PR', 'RN', 'CE', 'PB', 'PE', 'GO', 'SC',
       'RS', 'AC', 'AL', 'DF'], dtype=object)

In [42]:
filtered_weather['State'] = filtered_weather['Nome'].str.extract(r'-\s*(\w{2})')

In [52]:
# Rename columns in the weather_relevant DataFrame
weather_relevant = filtered_weather[['Data', 'State', 'UmidadeRelativa', 'TempMaxima', 'VelocidadeVento']]
weather_relevant = weather_relevant.rename(columns={
    'Data': 'order_estimated_delivery_date',
    'State': 'customer_state',
    'UmidadeRelativa' : 'Humidity',
    'TempMaxima' : 'TempMax',
    'VelocidadeVento' : 'SpeedWind'
})

In [53]:
weather_relevant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431371 entries, 0 to 431370
Data columns (total 5 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_estimated_delivery_date  431371 non-null  datetime64[ns]
 1   customer_state                 431371 non-null  object
 2   Humidity                       407236 non-null  float64
 3   TempMax                        134249 non-null  float64
 4   SpeedWind                      341740 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 16.5+ MB

In [55]:
merged_data = pd.merge(data, weather_relevant, on=['order_estimated_delivery_date', 'customer_state'], how='left')

# Check the resulting DataFrame
merged_data.info()

# Optionally, you can inspect the first few rows
merged_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544321 entries, 0 to 2544320
Data columns (total 29 columns):
 #   Column                               Dtype
---  ------                               -----
 0   order_id                             object
 1   customer_id                          object
 2   order_status                         object
 3   order_purchase_timestamp             datetime64[ns]
 4   order_approved_at                    datetime64[ns]
 5   order_delivered_timestamp            datetime64[ns]
 6   order_estimated_delivery_date        datetime64[ns]
 7   customer_zip_code_prefix             int64
 8   customer_city                        object
 9   customer_state                       object
 10  product_id                           object
 11  seller_id                            object
 12  price                                float64
 13  shipping_charges                     float64
 14  payment_sequential                   int64
 15  payment_type                         object
 16  payment_installments                 int64
 17  payment_value                        float64
 18  product_category_name                object
 19  is_delayed                           float64
 20  delivery_days_diff                   int64
 21  processing_time_category             object
 22  order_estimated_delivery_is_weekend  int64
 23  is_order_estimated_delivery_holiday  bool
 24  estimated_delivery_month             int32
 25  product_size_category                object
 26  Humidity                             float64
 27  TempMax                              float64
 28  SpeedWind                            float64
dtypes: bool(1), datetime64[ns](4), float64(7), int32(1), int64(5), object(11)
memory usage: 536.2+ MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,is_delayed,delivery_days_diff,processing_time_category,order_estimated_delivery_is_weekend,is_order_estimated_delivery_holiday,estimated_delivery_month,product_size_category,Humidity,TempMax,SpeedWind
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,0.0,-14,medium,0,False,11,medium,96.0,31.8,NaN
1,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,0.0,-14,medium,0,False,11,medium,79.0,NaN,NaN
2,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,0.0,-14,medium,0,False,11,medium,50.0,NaN,NaN
3,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,0.0,-14,medium,0,False,11,medium,75.0,27.0,3.0
4,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,58125,varzea paulista,SP,...,0.0,-14,medium,0,False,11,medium,72.0,NaN,4.0

In [58]:
merged_data.shape

(2544321, 29)

In [59]:
# Group by 'order_id' and aggregate the other columns
# For 'Humidity', 'TempMax', and 'SpeedWind', we take the max value
# For other columns, we take the first occurrence since they are identical for each order_id
aggregated_data = merged_data.groupby('order_id').agg({
    'customer_id': 'first',
    'order_status': 'first',
    'order_purchase_timestamp': 'first',
    'order_approved_at': 'first',
    'order_delivered_timestamp': 'first',
    'order_estimated_delivery_date': 'first',
    'customer_zip_code_prefix': 'first',
    'customer_city': 'first',
    'customer_state': 'first',
    'price': 'first',
    'shipping_charges': 'first',
    'payment_sequential': 'first',
    'payment_type': 'first',
    'payment_installments': 'first',
    'payment_value': 'first',
    'product_category_name': 'first',
    'is_delayed': 'first',
    'delivery_days_diff': 'first',
    'processing_time_category': 'first',
    'order_estimated_delivery_is_weekend': 'first',
    'is_order_estimated_delivery_holiday': 'first',
    'estimated_delivery_month': 'first',
    'product_size_category': 'first',
    'Humidity': 'max',  # Take the max value for Humidity
    'TempMax': 'max',   # Take the max value for TempMax
    'SpeedWind': 'max'   # Take the max value for SpeedWind
}).reset_index()

# Check the resulting DataFrame
aggregated_data.info()

# Optionally, inspect the first few rows
aggregated_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87427 entries, 0 to 87426
Data columns (total 27 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_id                             87427 non-null  object
 1   customer_id                          87427 non-null  object
 2   order_status                         87427 non-null  object
 3   order_purchase_timestamp             87427 non-null  datetime64[ns]
 4   order_approved_at                    87427 non-null  datetime64[ns]
 5   order_delivered_timestamp            87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date        87427 non-null  datetime64[ns]
 7   customer_zip_code_prefix             87427 non-null  int64
 8   customer_city                        87427 non-null  object
 9   customer_state                       87427 non-null  object
 10  price                                87427 non-null  float64
 11  shipping_charges                     87427 non-null  float64
 12  payment_sequential                   87427 non-null  int64
 13  payment_type                         87427 non-null  object
 14  payment_installments                 87427 non-null  int64
 15  payment_value                        87427 non-null  float64
 16  product_category_name                87427 non-null  object
 17  is_delayed                           87422 non-null  float64
 18  delivery_days_diff                   87427 non-null  int64
 19  processing_time_category             87427 non-null  object
 20  order_estimated_delivery_is_weekend  87427 non-null  int64
 21  is_order_estimated_delivery_holiday  87427 non-null  bool
 22  estimated_delivery_month             87427 non-null  int32
 23  product_size_category                87427 non-null  object
 24  Humidity                             87037 non-null  float64
 25  TempMax                              86919 non-null  float64
 26  SpeedWind                            85267 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(7), int32(1), int64(5), object(9)
memory usage: 17.1+ MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,is_delayed,delivery_days_diff,processing_time_category,order_estimated_delivery_is_weekend,is_order_estimated_delivery_holiday,estimated_delivery_month,product_size_category,Humidity,TempMax,SpeedWind
0,001gkk6BwKEB,xKv2nBFnvcwS,delivered,2018-04-16 14:01:44,2018-04-16 14:32:36,2018-04-20 19:42:15,2018-05-03,44710,sao paulo,SP,...,0.0,-13,medium,0,False,5,large,92.0,33.2,4.0000
1,0029bAIZFMKA,Xcm6u682SuQQ,delivered,2018-02-17 15:04:06,2018-02-20 07:06:53,2018-03-22 23:51:19,2018-03-15,87033,londrina,PR,...,1.0,7,slow,0,False,3,small,98.0,36.3,6.5000
2,002Jk8hp9Bhy,l0HoYdeR1BJM,delivered,2018-04-24 09:27:39,2018-04-25 03:51:36,2018-04-26 18:17:28,2018-05-17,45910,itaquaquecetuba,SP,...,0.0,-21,slow,0,False,5,medium,94.0,29.8,3.6000
3,002ohHsWSKrP,z5refCsXE1nS,delivered,2018-05-17 17:09:33,2018-05-17 20:32:27,2018-05-21 20:31:47,2018-05-25,24358,guarulhos,SP,...,0.0,-4,slow,0,False,5,small,91.0,30.0,4.0000
4,0041NijdAYB0,XMxGRoDyISTv,delivered,2018-07-10 10:32:53,2018-07-10 10:45:39,2018-07-25 12:36:45,2018-08-01,68675,aracaju,SE,...,0.0,-7,medium,0,False,8,large,88.0,30.0,2.5722

In [60]:
aggregated_data.shape

(87427, 27)

## **Explore categorical features:**

In [64]:
data_cat = aggregated_data[['customer_city', 'customer_state', 'payment_type', 'product_category_name','processing_time_category','estimated_delivery_month']]

# Print the unique values for each categorical column
for c in data_cat.columns:
    print(f"Unique values in '{c}':")
    print(data_cat[c].unique())
    print("\n")

Unique values in 'customer_city':
['sao paulo' 'londrina' 'itaquaquecetuba' ... 'sao jose do rio claro'
 'boquira' 'corbelia']


Unique values in 'customer_state':
['SP' 'PR' 'SE' 'BA' 'RS' 'RJ' 'MS' 'MG' 'RN' 'ES' 'SC' 'AL' 'GO' 'DF'
 'CE' 'MA' 'PE' 'MT' 'RO' 'PA' 'PB' 'AM' 'AC' 'PI' 'TO' 'AP' 'RR']


Unique values in 'payment_type':
['credit_card' 'wallet' 'debit_card' 'voucher']


Unique values in 'product_category_name':
['toys' 'telephony' 'housewares' 'computers_accessories' 'cool_stuff'
 'watches_gifts' 'office_furniture' 'bed_bath_table' 'electronics'
 'stationery' 'auto' 'health_beauty' 'garden_tools'
 'construction_tools_construction' 'market_place' 'furniture_decor'
 'perfumery' 'baby' 'audio' 'food' 'sports_leisure' 'fashion_shoes'
 'pet_shop' 'home_appliances_2' 'unknown' 'home_appliances'
 'books_technical' 'furniture_living_room' 'computers' 'home_construction'
 'agro_industry_and_commerce' 'books_general_interest'
 'fashion_bags_accessories' 'consoles_games' 'home_confort' 'food_drink'
 'small_appliances_home_oven_and_coffee' 'air_conditioning' 'music'
 'luggage_accessories' 'drinks' 'industry_commerce_and_business'
 'costruction_tools_garden' 'construction_tools_safety'
 'christmas_supplies' 'small_appliances' 'musical_instruments'
 'construction_tools_lights' 'costruction_tools_tools'
 'kitchen_dining_laundry_garden_furniture' 'arts_and_craftmanship'
 'fixed_telephony' 'signaling_and_security' 'tablets_printing_image'
 'party_supplies' 'flowers' 'fashio_female_clothing'
 'fashion_underwear_beach' 'la_cuisine' 'dvds_blu_ray' 'furniture_bedroom'
 'fashion_male_clothing' 'books_imported' 'cine_photo' 'fashion_sport'
 'fashion_childrens_clothes' 'art' 'home_comfort_2'
 'security_and_services' 'furniture_mattress_and_upholstery'
 'diapers_and_hygiene']


Unique values in 'processing_time_category':
['medium' 'slow' 'fast']


Unique values in 'estimated_delivery_month':
[ 5  3  8  7  9  2 12 10  4  1  6 11]

In [67]:
aggregated_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87427 entries, 0 to 87426
Data columns (total 27 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_id                             87427 non-null  object
 1   customer_id                          87427 non-null  object
 2   order_status                         87427 non-null  object
 3   order_purchase_timestamp             87427 non-null  datetime64[ns]
 4   order_approved_at                    87427 non-null  datetime64[ns]
 5   order_delivered_timestamp            87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date        87427 non-null  datetime64[ns]
 7   customer_zip_code_prefix             87427 non-null  int64
 8   customer_city                        87427 non-null  object
 9   customer_state                       87427 non-null  object
 10  price                                87427 non-null  float64
 11  shipping_charges                     87427 non-null  float64
 12  payment_sequential                   87427 non-null  int64
 13  payment_type                         87427 non-null  object
 14  payment_installments                 87427 non-null  int64
 15  payment_value                        87427 non-null  float64
 16  product_category_name                87427 non-null  object
 17  is_delayed                           87422 non-null  float64
 18  delivery_days_diff                   87427 non-null  int64
 19  processing_time_category             87427 non-null  object
 20  order_estimated_delivery_is_weekend  87427 non-null  int64
 21  is_order_estimated_delivery_holiday  87427 non-null  bool
 22  estimated_delivery_month             87427 non-null  int32
 23  product_size_category                87427 non-null  object
 24  Humidity                             87037 non-null  float64
 25  TempMax                              86919 non-null  float64
 26  SpeedWind                            85267 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(7), int32(1), int64(5), object(9)
memory usage: 17.1+ MB

In [70]:
# Check for missing values in each column
missing_values = aggregated_data.isnull().sum()
# Display the missing values
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
order_purchase_timestamp                  0
order_approved_at                         0
order_delivered_timestamp                 0
order_estimated_delivery_date             0
customer_city                             0
customer_state                            0
price                                     0
shipping_charges                          0
payment_type                              0
payment_value                             0
product_category_name                     0
is_delayed                                5
delivery_days_diff                        0
processing_time_category                  0
order_estimated_delivery_is_weekend       0
is_order_estimated_delivery_holiday       0
estimated_delivery_month                  0
product_size_category                     0
Humidity                                390
TempMax                                 508
SpeedWind                              2160
dtype: int64

In [71]:
# Impute missing values for numerical columns with the median
aggregated_data['Humidity'] = aggregated_data['Humidity'].fillna(aggregated_data['Humidity'].median())
aggregated_data['TempMax'] = aggregated_data['TempMax'].fillna(aggregated_data['TempMax'].median())
aggregated_data['SpeedWind'] = aggregated_data['SpeedWind'].fillna(aggregated_data['SpeedWind'].median())

# Impute missing values for the binary column 'is_delayed' with the mode
aggregated_data['is_delayed'] = aggregated_data['is_delayed'].fillna(aggregated_data['is_delayed'].mode()[0])

# Check if missing values have been imputed
print(aggregated_data.isnull().sum())

order_purchase_timestamp               0
order_approved_at                      0
order_delivered_timestamp              0
order_estimated_delivery_date          0
customer_city                          0
customer_state                         0
price                                  0
shipping_charges                       0
payment_type                           0
payment_value                          0
product_category_name                  0
is_delayed                             0
delivery_days_diff                     0
processing_time_category               0
order_estimated_delivery_is_weekend    0
is_order_estimated_delivery_holiday    0
estimated_delivery_month               0
product_size_category                  0
Humidity                               0
TempMax                                0
SpeedWind                              0
dtype: int64

## Dropping Unnecessary Identifiers and Irrelevant Features

In [68]:
columns_to_drop = ['order_status', 'order_id', 'customer_id', 
                   'customer_zip_code_prefix', 'payment_sequential', 
                   'payment_installments']
columns_to_drop = [col for col in columns_to_drop if col in aggregated_data.columns]
aggregated_data = aggregated_data.drop(columns=columns_to_drop)
aggregated_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87427 entries, 0 to 87426
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_purchase_timestamp             87427 non-null  datetime64[ns]
 1   order_approved_at                    87427 non-null  datetime64[ns]
 2   order_delivered_timestamp            87427 non-null  datetime64[ns]
 3   order_estimated_delivery_date        87427 non-null  datetime64[ns]
 4   customer_city                        87427 non-null  object
 5   customer_state                       87427 non-null  object
 6   price                                87427 non-null  float64
 7   shipping_charges                     87427 non-null  float64
 8   payment_type                         87427 non-null  object
 9   payment_value                        87427 non-null  float64
 10  product_category_name                87427 non-null  object
 11  is_delayed                           87422 non-null  float64
 12  delivery_days_diff                   87427 non-null  int64
 13  processing_time_category             87427 non-null  object
 14  order_estimated_delivery_is_weekend  87427 non-null  int64
 15  is_order_estimated_delivery_holiday  87427 non-null  bool
 16  estimated_delivery_month             87427 non-null  int32
 17  product_size_category                87427 non-null  object
 18  Humidity                             87037 non-null  float64
 19  TempMax                              86919 non-null  float64
 20  SpeedWind                            85267 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(7), int32(1), int64(2), object(6)
memory usage: 13.1+ MB

In [73]:
# Save to a specific folder
aggregated_data.to_csv('/kaggle/working/orders_data.csv', index=False)